---
out_dir: results
root_dir: ''
metric_agg: argmax
metric_best: roc_auc
seed: 1
dataset:
  format: custom
  name: ETH
  table: ETH_PHISHING
model:
  type: MPNN
  loss_fun: ce
  w_ce1: 1.0
  w_ce2: 6.0
gnn:
  head: NodePredictionHead
  dim_in: 1
  dim_out: 2
  edge_dim: 2
  dim_inner: 20
  layers_pre_mp: 1
  layers_mp: 2
  layers_post_mp: 1
  layer_type: pna
  act: relu
  dropout: 0.2
  agg: mean
  normalize_adj: false
  add_encodings: true
  encodings_file: ''
train:
  mode: eth_train
  batch_size: 512
  num_neighs: [100, 100]
optim:
  optimizer: adam
  weight_decay: 1e-4
  base_lr: 0.0005
  max_epoch: 100

save_model: false
